"""empty message

Revision ID: 25ad7d15095d
Revises: 329b51d70634
Create Date: 2021-12-19 23:44:12.814670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ad7d15095d'
down_revision = '329b51d70634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parentz',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parentz',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
