"""empty message

Revision ID: 30ef6aa2005e
Revises: e38c28b18d0a
Create Date: 2021-12-19 22:35:09.042335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ef6aa2005e'
down_revision = 'e38c28b18d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parentz', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'comments', ['parentz'], ['item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parentz')
    # ### end Alembic commands ###
