"""empty message

Revision ID: 329b51d70634
Revises: 30ef6aa2005e
Create Date: 2021-12-19 22:42:16.258432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329b51d70634'
down_revision = '30ef6aa2005e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('news', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'source')
    op.drop_column('comments', 'source')
    # ### end Alembic commands ###
