"""empty message

Revision ID: 63d770608c53
Revises: 96f62ee87936
Create Date: 2021-12-14 02:53:57.628904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d770608c53'
down_revision = '96f62ee87936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('kids', sa.String(), nullable=True))
    op.alter_column('news', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('news', 'kids')
    # ### end Alembic commands ###
